alltoys/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', include('toys.urls', namespace='toys')),
    path('dashboard/', RedirectView.as_view(url='/')),  # Bunda RedirectView methodi bir
    # nechta urlga bitta sahifani berishga yordam beradi
    path('admin/', admin.site.urls),
    path(
        'admin/password_reset/',
        auth_views.PasswordResetView.as_view(),
        name='admin_password_reset',
    ),
    path(
        'admin/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),
    path('__debug__/', include(debug_toolbar.urls)),
    path('api-markets/', include('markets.api.urls')),
]

toys/urls.py
from django.urls import path
from toys import views

app_name = 'toys'
urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.SignOutView.as_view(), name='logout'),
    path('toys/', views.ToysListView.as_view(), name='toys'),
    path('toys/create', views.ToyCreateView.as_view(), name='toys-create'),
    path('toys/<int:pk>', views.ToyDetailView.as_view(), name='toy_detail'),
    path('users/', views.show_users, name='show_users'),
    path('cabinet/', views.CabinetView, name='cabinet'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('employee/add', views.EmployeeCreateView.as_view(), name='employee-add'),
    path('employee/list/', views.employee_list, name='employee-list'),
    path('employee/list/<int:pk>/edit', views.employee_edit, name='employee-edit')
]

toys/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class ActiveObjectsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class BaseModel(models.Model):
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Address(models.Model):
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100, null=True, blank=True)
    zip_code = models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Address'


class User(AbstractUser, BaseModel):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    address = models.OneToOneField(Address, on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        db_table = 'user'
        verbose_name_plural = 'Users'


class Tag(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Toy(BaseModel):
    name = models.CharField(max_length=100)
    user = models.ForeignKey(User, related_name='toys', on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag, related_name='toys')
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('toys:toy_detail', args=(self.id,))


class Company(models.Model):
    company_name = models.CharField(max_length=100)
    company_email = models.EmailField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.company_name


class Employee(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=100)
    age = models.IntegerField()
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    address = models.ForeignKey(Address, on_delete=models.PROTECT)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

toys/forms/employee_add.py
from django import forms
from toys.models import Employee


class EmployeeModelForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

toys/forms/login.py
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    pass

toys/forms/sign_up.py
from django.contrib.auth.forms import UserCreationForm

from toys.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name', 'last_name', 'username', 'password1', 'password2', 'phone'
        ]

toys/forms/toy.py
from django import forms
from toys.models import Toy


class ToyForm(forms.Form):
    name = forms.CharField(label='Toy name', required=True)
    description = forms.CharField(required=False)


class ToyModelForm(forms.ModelForm):
    class Meta:
        model = Toy
        fields = ['name', 'description', 'price']

toys/forms/user.py
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    pass

toys/views.py
from django.contrib.auth.views import LogoutView
from django.shortcuts import redirect, resolve_url
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.base import View, TemplateView
from toys.forms.employee_add import EmployeeModelForm
from toys.forms.sign_up import SignUpForm
from toys.forms.toy import ToyModelForm
from toys.forms.login import LoginForm
from toys.models import Toy, User, Employee
from django.shortcuts import render
from django.contrib.auth import login, authenticate


class DashboardView(TemplateView):
    template_name = 'toys/dashboard.html'
    extra_context = {'welcome_text': 'Welcome to AllToys!'}


# Bu method orqali extra_contextni o'zgartirish mumkin
'''    def get_context_data(self, **kwargs):          
        super().get_context_data(**kwargs)
        self.extra_context['welcome_text'] = 'AllToysga xush kelibsiz'
        if self.extra_context is not None:
            self.extra_context.update(self.extra_context)
            return self.extra_context'''


# class DashboardView(View):
#     def get(self, request):
#         return render(request, template_name='toys/dashboard.html', context={'welcome_text': 'Welcome to AllToys!'})


class ToysListView(ListView):
    model = Toy
    template_name = 'toys/toys.html'
    queryset = Toy.objects.filter()

    def get_queryset(self):
        toys = Toy.objects.filter(created_at__year=timezone.now().year)
        return toys


class ToyDetailView(DetailView):
    model = Toy
    template_name = 'toys/toy_detail.html'


class ToyCreateView(View):
    template_name = 'toys/toy.html'

    def get(self, request):
        if not request.user.is_authenticated:
            url = resolve_url('toys:login') + '?next=' + request.get_full_path()
            return redirect(url)
        form = ToyModelForm()
        return render(request, self.template_name, {
            'form': form
        })

    def post(self, request):
        form = ToyModelForm(data=request.POST)
        if form.is_valid():
            toy = form.save()
            return redirect(to='toys:toy_detail', pk=toy.id)
        context = {'form': form}
        return render(request, self.template_name, context)


class LoginView(View):
    template_name = 'toys/login.html'

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            # username = form.cleaned_data.get('username')
            # password = form.cleaned_data.get('password')
            user = form.get_user()
            login(request, user)

            redirect_to = request.GET.get('next')
            if not redirect_to:
                redirect_to = 'toys:cabinet'
            return redirect(to=redirect_to)
        context = {'form': form}
        return render(request, self.template_name, context)


# def signup(request):
#     if request.method == 'POST':
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=password)
#             login(request, user)
#             return redirect('toys:login')
#     else:
#         form = SignUpForm()
#     return render(request, 'toys/signup.html', {'form': form})


class SignUp(TemplateView):
    template_name = 'toys/signup.html'

    def get(self, request, *args, **kwargs):
        form = SignUpForm()
        return render(request, 'toys/signup.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('toys:login')
        return render(request, 'toys/signup.html', {'form': form})


class SignOutView(LogoutView):
    pass


def show_users(request):
    users = User.objects.all()
    return render(request, 'toys/show_users.html', context={'users_list': users})


def CabinetView(request):
    username = request.user
    return render(request, 'toys/cabinet.html', context={'username': username})


class EmployeeCreateView(View):
    template_name = 'toys/employee.html'

    def get(self, request):
        if not request.user.is_authenticated:
            url = resolve_url('toys:login') + '?next=' + request.get_full_path()
            return redirect(url)
        form = EmployeeModelForm()
        return render(request, self.template_name, {
            'form': form
        })

    def post(self, request):
        form = EmployeeModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='toys:employee-list')
        context = {'form': form}
        return render(request, self.template_name, context)


def employee_list(request):
    context = {'employee_list': Employee.objects.all()}
    return render(request, 'toys/employee_list.html', context)


def employee_edit(request, pk=None):
    instance = Employee.objects.get(id=pk)
    if request.method == 'POST':
        form = EmployeeModelForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('toys:employee-list')
    else:
        form = EmployeeModelForm(instance=instance)
    return render(request, 'toys/employee_edit.html', {'form': form})

toys/templates/toys/cabinet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to Cabinet</title>
</head>
<body>
<div>
    {{ username }}
</div>
</body>
</html>

toys/templates/toys/dashboard.html
{% extends 'toys/layout.html' %}
{% block page_title %}
    All Toys Dashboard
{% endblock %}
{% block page_header %}
    {{ welcome_text }}
{% endblock %}

{% block page_content %}
    Welcome to All Toys Dashboard!
{% endblock %}

toys/templates/toys/employee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add new Employee</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

toys/templates/toys/employee_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add new Employee</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

toys/templates/toys/employee_list.html
{% extends 'toys/layout.html' %}
{% load any %}
{% block page_title %}
    Welcome to Employee list
{% endblock %}
{% block page_header %}
    Welcome to Employee list
    <hr>
{% endblock %}
{% block page_navbar %}
    <table class="table table-borderless">
        <thead class="border-bottom font-weight-bold">
        <tr>
            <td>First name</td>
            <td>Last name</td>
            <td>Phone number</td>
            <td>Email</td>
        </tr>
        </thead>
        <tbody>
        {% render_employee_list employee_list %}
        </tbody>
    </table>
{% endblock %}
{% block page_content %}
{% endblock %}

toys/templates/toys/employee_list_for_render.html
{% for employee in employee_list %}
    <tr>
        <td>{{ employee.first_name }}</td>
        <td>{{ employee.last_name }}</td>
        <td>{{ employee.phone }}</td>
        <td>{{ employee.email }}</td>
        <td><a href="{% url 'toys:employee-edit' pk=employee.pk %}">Edit</a></td>
    </tr>
{% endfor %}

toys/templates/toys/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title %}{% endblock %}</title>
</head>
<body>
<div>
    {% block page_header %}
    {% endblock %}
</div>
<div>
    {% block page_navbar %}
    <table>
        <tr>
            <td style="width: 100px"><a href="{% url 'toys:toys' %}">Toys</a></td>
            <td style="width: 100px"><a href="#">Users</a></td>
        </tr>
    </table>
    {% endblock %}
    <hr>
</div>
<div>
    {% block page_content %}
    {% endblock %}
</div>

</body>
</html>

toys/templates/toys/login.html
{% extends 'toys/layout.html' %}
{% block page_title %}
    Login to All Toys
{% endblock %}
{% block page_header %}
{% endblock %}
{% block page_navbar %}
{% endblock %}

{% block page_content %}
    <h3>Sign in</h3>
    <form method="post">
        {% csrf_token %}
        {{ form.username }}
        {{ form.password }}
        {{ form.non_field_errors }}
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
{% endblock %}

toys/templates/toys/show_users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for user in users_list %}
    <p>{{ user.first_name }}  {{ user.last_name }}</p>
{% endfor %}
</body>
</html>

toys/templates/toys/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AllToys - dashboard</title>
</head>
<body>
<h3>Sign in</h3>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Signup</button>
</form>
</body>
</html>

toys/templates/toys/toy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create new Toy</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Save">
</form>
</body>
</html>

toys/templates/toys/toy_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AllToys - Toy detail</title>
</head>
<body>
<div>
    All Toys
</div>
<div>
    <table>
        <tr>
            <td style="width: 100px"><a href="{% url 'toys:toys' %}">Toys</a></td>
            <td style="width: 100px"><a href="#">Users</a></td>
        </tr>
    </table>
    <hr>
    <div>
        {{ object.name }}
    </div>

</div>
</body>
</html>

toys/templates/toys/toy_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

</body>
</html>

toys/templates/toys/toy_list.html
{% for toy in toys %}
    <tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ toy.name }}</td>
    </tr>
{% endfor %}